// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	didexchange "github.com/hyperledger/aries-framework-go/pkg/client/didexchange"
	mock "github.com/stretchr/testify/mock"
)

// provider is an autogenerated mock type for the provider type
type provider struct {
	mock.Mock
}

// GetDIDClient provides a mock function with given fields:
func (_m *provider) GetDIDClient() (*didexchange.Client, error) {
	ret := _m.Called()

	var r0 *didexchange.Client
	if rf, ok := ret.Get(0).(func() *didexchange.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*didexchange.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
