// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "github.com/hyperledger/aries-framework-go/pkg/framework/context"
	datastore "github.com/scoir/canis/pkg/datastore"

	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the provider type
type Provider struct {
	mock.Mock
}

// GetAriesContext provides a mock function with given fields:
func (_m *Provider) GetAriesContext() (*context.Provider, error) {
	ret := _m.Called()

	var r0 *context.Provider
	if rf, ok := ret.Get(0).(func() *context.Provider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*context.Provider)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDatastore provides a mock function with given fields:
func (_m *Provider) GetDatastore() (datastore.Store, error) {
	ret := _m.Called()

	var r0 datastore.Store
	if rf, ok := ret.Get(0).(func() datastore.Store); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(datastore.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEdgeAgentSecret provides a mock function with given fields:
func (_m *Provider) GetEdgeAgentSecret() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetExternal provides a mock function with given fields:
func (_m *Provider) GetExternal() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
