# Copyright Scoir Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

coverage:
  ci:
    - "github.com"
  status:
    project:
      default:
        target: 0% #yup
    patch:
      default:
        target: 85%
        only_pulls: true
