// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: didcomm/doorman/api/canis-didcomm-doorman.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InvitationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID string `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InvitationRequest) Reset() {
	*x = InvitationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_didcomm_doorman_api_canis_didcomm_doorman_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationRequest) ProtoMessage() {}

func (x *InvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_didcomm_doorman_api_canis_didcomm_doorman_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationRequest.ProtoReflect.Descriptor instead.
func (*InvitationRequest) Descriptor() ([]byte, []int) {
	return file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescGZIP(), []int{0}
}

func (x *InvitationRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *InvitationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InvitationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invitation string `protobuf:"bytes,1,opt,name=Invitation,proto3" json:"Invitation,omitempty"`
}

func (x *InvitationResponse) Reset() {
	*x = InvitationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_didcomm_doorman_api_canis_didcomm_doorman_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationResponse) ProtoMessage() {}

func (x *InvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_didcomm_doorman_api_canis_didcomm_doorman_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationResponse.ProtoReflect.Descriptor instead.
func (*InvitationResponse) Descriptor() ([]byte, []int) {
	return file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescGZIP(), []int{1}
}

func (x *InvitationResponse) GetInvitation() string {
	if x != nil {
		return x.Invitation
	}
	return ""
}

var File_didcomm_doorman_api_canis_didcomm_doorman_proto protoreflect.FileDescriptor

var file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x6e, 0x69, 0x73, 0x2d, 0x64, 0x69, 0x64, 0x63,
	0x6f, 0x6d, 0x6d, 0x2d, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x22, 0x41, 0x0a, 0x11, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a,
	0x12, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0x55, 0x0a, 0x07, 0x44, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x12, 0x4a,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x2e, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x69,
	0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x64, 0x69,
	0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescOnce sync.Once
	file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescData = file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDesc
)

func file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescGZIP() []byte {
	file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescOnce.Do(func() {
		file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescData = protoimpl.X.CompressGZIP(file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescData)
	})
	return file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDescData
}

var file_didcomm_doorman_api_canis_didcomm_doorman_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_didcomm_doorman_api_canis_didcomm_doorman_proto_goTypes = []interface{}{
	(*InvitationRequest)(nil),  // 0: didcomm.InvitationRequest
	(*InvitationResponse)(nil), // 1: didcomm.InvitationResponse
}
var file_didcomm_doorman_api_canis_didcomm_doorman_proto_depIdxs = []int32{
	0, // 0: didcomm.Doorman.GetInvitation:input_type -> didcomm.InvitationRequest
	1, // 1: didcomm.Doorman.GetInvitation:output_type -> didcomm.InvitationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_didcomm_doorman_api_canis_didcomm_doorman_proto_init() }
func file_didcomm_doorman_api_canis_didcomm_doorman_proto_init() {
	if File_didcomm_doorman_api_canis_didcomm_doorman_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_didcomm_doorman_api_canis_didcomm_doorman_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvitationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_didcomm_doorman_api_canis_didcomm_doorman_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvitationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_didcomm_doorman_api_canis_didcomm_doorman_proto_goTypes,
		DependencyIndexes: file_didcomm_doorman_api_canis_didcomm_doorman_proto_depIdxs,
		MessageInfos:      file_didcomm_doorman_api_canis_didcomm_doorman_proto_msgTypes,
	}.Build()
	File_didcomm_doorman_api_canis_didcomm_doorman_proto = out.File
	file_didcomm_doorman_api_canis_didcomm_doorman_proto_rawDesc = nil
	file_didcomm_doorman_api_canis_didcomm_doorman_proto_goTypes = nil
	file_didcomm_doorman_api_canis_didcomm_doorman_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DoormanClient is the client API for Doorman service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DoormanClient interface {
	GetInvitation(ctx context.Context, in *InvitationRequest, opts ...grpc.CallOption) (*InvitationResponse, error)
}

type doormanClient struct {
	cc grpc.ClientConnInterface
}

func NewDoormanClient(cc grpc.ClientConnInterface) DoormanClient {
	return &doormanClient{cc}
}

func (c *doormanClient) GetInvitation(ctx context.Context, in *InvitationRequest, opts ...grpc.CallOption) (*InvitationResponse, error) {
	out := new(InvitationResponse)
	err := c.cc.Invoke(ctx, "/didcomm.Doorman/GetInvitation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoormanServer is the server API for Doorman service.
type DoormanServer interface {
	GetInvitation(context.Context, *InvitationRequest) (*InvitationResponse, error)
}

// UnimplementedDoormanServer can be embedded to have forward compatible implementations.
type UnimplementedDoormanServer struct {
}

func (*UnimplementedDoormanServer) GetInvitation(context.Context, *InvitationRequest) (*InvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvitation not implemented")
}

func RegisterDoormanServer(s *grpc.Server, srv DoormanServer) {
	s.RegisterService(&_Doorman_serviceDesc, srv)
}

func _Doorman_GetInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoormanServer).GetInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.Doorman/GetInvitation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoormanServer).GetInvitation(ctx, req.(*InvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Doorman_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didcomm.Doorman",
	HandlerType: (*DoormanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInvitation",
			Handler:    _Doorman_GetInvitation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "didcomm/doorman/api/canis-didcomm-doorman.proto",
}
