###############################################################
#
#  Datastore configuration
#
###############################################################
datastore:
  database: mongo
  mongo:
     url: "mongodb://172.17.0.1:27017"
     database: "canis"


###############################################################
#
#  Runtime configuration
#
###############################################################
execution:
  runtime: docker
  docker:
    home: /tmp/canis

###############################################################
#
#  Steward configuration
#
###############################################################
steward:
  dbpath: /tmp/canis/steward

  wsinbound:
    host: 0.0.0.0
    port: 7777
  grpc:
    host: 0.0.0.0
    port: 7778
  grpcBridge:
    host: 0.0.0.0
    port: 7779

###############################################################
#
#  Agent configuration
#
###############################################################
agent:
  dbpath: /tmp/canis/agent
  wsinbound:
    host: 0.0.0.0
    port: 8887
  grpc:
    host: 0.0.0.0
    port: 8888
  grpcBridge:
    host: 0.0.0.0
    port: 8889

