#
# Copyright Scoir, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM amd64/ubuntu:bionic

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y ca-certificates

COPY ./ursa_0.3.4-1_amd64.deb /tmp
COPY ./libindy_vdr.so /usr/lib

RUN apt install /tmp/ursa_0.3.4-1_amd64.deb -y
RUN ldconfig
