#
# Copyright Scoir, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

FROM canislabs/canisbuild:golang-1.15 as golang

ADD . $GOPATH/src/github.com/scoir/canis
WORKDIR $GOPATH/src/github.com/scoir/canis
ENV EXECUTABLES go git

FROM golang as canis
ENV PATH="/root/go/bin:${PATH}"
RUN make tools; make build


FROM canislabs/canisbase:latest as base
COPY --from=canis /src/github.com/scoir/canis/bin/canis-apiserver /usr/local/bin/canis-apiserver
COPY --from=canis /src/github.com/scoir/canis/bin/canis-didcomm-issuer /usr/local/bin/canis-didcomm-issuer
COPY --from=canis /src/github.com/scoir/canis/bin/canis-didcomm-verifier /usr/local/bin/canis-didcomm-verifier
COPY --from=canis /src/github.com/scoir/canis/bin/canis-didcomm-doorman /usr/local/bin/canis-didcomm-doorman
COPY --from=canis /src/github.com/scoir/canis/bin/canis-didcomm-mediator /usr/local/bin/canis-didcomm-mediator
COPY --from=canis /src/github.com/scoir/canis/bin/canis-didcomm-cloudagent /usr/local/bin/canis-didcomm-cloudagent
COPY --from=canis /src/github.com/scoir/canis/bin/canis-didcomm-lb /usr/local/bin/canis-didcomm-lb
COPY --from=canis /src/github.com/scoir/canis/bin/http-indy-resolver /usr/local/bin/http-indy-resolver
COPY --from=canis /src/github.com/scoir/canis/bin/canis-webhook-notifier /usr/local/bin/canis-webhook-notifier
COPY --from=canis /src/github.com/scoir/canis/bin/sirius /usr/local/bin/sirius
COPY --from=canis /src/github.com/scoir/canis/static /usr/local/canis/static

WORKDIR /usr/local/canis
