#
# Copyright Scoir, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM golangci/golangci-lint:v1.31.0

RUN apt-get update -y
RUN apt-get upgrade -y

COPY ./libindy_vdr.so /usr/lib

RUN ldconfig
