###############################################################
#
#  AMQP Server (rabbitMQ)
#
###############################################################
amqp:
  user: canis
  password: canis
  host: 172.17.0.1
  port: 5672
  vhost: canis
