###############################################################
#
#  DIDComm Mediator
#
###############################################################
inbound:
  host: 0.0.0.0
  httpPort: 10001
  wsPort: 10002
  external: "ws://172.17.0.1:10002"

###############################################################
#
#  GRPC Server
#
###############################################################
mediator:
  grpc:
    host: 0.0.0.0
    port: 10003
  edgeAgentSecret: ArwXoACJgOleVZ2PY7kXn7rA0II0mHYDhc6WrBH8fDAc
