###############################################################
#
#  DIDComm Server
#
###############################################################
api:
  grpc:
    host: 0.0.0.0
    port: 7776
inbound:
  external: ws://0.0.0.0:3001
