###############################################################
#
#  API Server
#
###############################################################
api:
  grpc:
    host: 0.0.0.0
    port: 7778
  grpcBridge:
    host: 0.0.0.0
    port: 7779

###############################################################
#
#  Doorman configuration
#
###############################################################
doorman:
  grpc:
    host: 172.17.0.1
    port: 8886

###############################################################
#
#  Issuer configuration
#
###############################################################
issuer:
  grpc:
    host: 172.17.0.1
    port: 7776

###############################################################
#
#  Loadbalancer configuration
#
###############################################################
loadbalancer:
  grpc:
    host: 172.17.0.1
    port: 9996
