###############################################################
#
#  Ledger-store configuration
#
###############################################################
ledgerstore:
  database: mongodb
  url: "mongodb://172.17.0.1:27017"
