###############################################################
#
#  Wallet configuration
#
###############################################################
wallet:
  masterLockKey: "OTsonzgWMNAqR24bgGcZVHVBB_oqLoXntW4s_vCs6uQ="
