// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	decorator "github.com/hyperledger/aries-framework-go/pkg/didcomm/protocol/decorator"

	mock "github.com/stretchr/testify/mock"

	schema "github.com/scoir/canis/pkg/schema"
)

// PresentationEngine is an autogenerated mock type for the PresentationEngine type
type PresentationEngine struct {
	mock.Mock
}

// Accept provides a mock function with given fields: typ
func (_m *PresentationEngine) Accept(typ string) bool {
	ret := _m.Called(typ)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(typ)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RequestPresentation provides a mock function with given fields: name, version, attrInfo, predicateInfo
func (_m *PresentationEngine) RequestPresentation(name string, version string, attrInfo map[string]*schema.IndyProofRequestAttr, predicateInfo map[string]*schema.IndyProofRequestPredicate) (*decorator.AttachmentData, error) {
	ret := _m.Called(name, version, attrInfo, predicateInfo)

	var r0 *decorator.AttachmentData
	if rf, ok := ret.Get(0).(func(string, string, map[string]*schema.IndyProofRequestAttr, map[string]*schema.IndyProofRequestPredicate) *decorator.AttachmentData); ok {
		r0 = rf(name, version, attrInfo, predicateInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*decorator.AttachmentData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, map[string]*schema.IndyProofRequestAttr, map[string]*schema.IndyProofRequestPredicate) error); ok {
		r1 = rf(name, version, attrInfo, predicateInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestPresentationFormat provides a mock function with given fields:
func (_m *PresentationEngine) RequestPresentationFormat() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Verify provides a mock function with given fields: presentation, request, theirDID, myDID
func (_m *PresentationEngine) Verify(presentation []byte, request []byte, theirDID string, myDID string) error {
	ret := _m.Called(presentation, request, theirDID, myDID)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, string, string) error); ok {
		r0 = rf(presentation, request, theirDID, myDID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
