// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PresentationEngine is an autogenerated mock type for the PresentationEngine type
type PresentationEngine struct {
	mock.Mock
}

// Accept provides a mock function with given fields: typ
func (_m *PresentationEngine) Accept(typ string) bool {
	ret := _m.Called(typ)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(typ)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
