apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-apiserver-config
  labels:
    app: {{ include "canis.fullname" . }}-canis-apiserver
data:
  canis-apiserver-config.yaml: |-
    ###############################################################
    #
    #  Datastore configuration
    #
    ###############################################################
    datastore:
      {{- toYaml .Values.datastore | nindent 6 }}

    ###############################################################
    #
    #  Ledger-store configuration
    #
    ###############################################################
    ledgerstore:
      {{- toYaml .Values.ledgerstore | nindent 6 }}

    ###############################################################
    #
    #  Wallet configuration
    #
    ###############################################################
    wallet:
      masterLockKey: {{ .Values.wallet.masterLockKey }}
    
    ###############################################################
    #
    #  API Server
    #
    ###############################################################
    api:
      grpc:
        host: 0.0.0.0
        port: {{ .Values.apiserver.grpc.port }}
      grpcBridge:
        host: 0.0.0.0
        port: {{ .Values.apiserver.grpcBridge.port }}
    
    ###############################################################
    #
    #  Doorman configuration
    #
    ###############################################################
    doorman:
      grpc:
        host: canis-didcomm-doorman
        port: {{ .Values.doorman.grpc.port }}
    
    ###############################################################
    #
    #  Issuer configuration
    #
    ###############################################################
    issuer:
      grpc:
        host: canis-didcomm-issuer
        port: {{ .Values.issuer.grpc.port }}
    
    ###############################################################
    #
    #  Loadbalancer configuration
    #
    ###############################################################
    loadbalancer:
      grpc:
        host: canis-didcomm-lb
        port: {{ .Values.loadbalancer.grpc.port }}
    
    ###############################################################
    #
    #  Indy VDR Configuration
    #
    ###############################################################
    genesisFile: {{- .Files.Get "indy/genesis.txn" | toYaml | nindent 4}}

    ###############################################################
    #
    #  Aries Indy VDRI Configuration
    #
    ###############################################################
    aries:
      vdri:
        - type: indy
          method: "scr"
          genesisFile: {{- .Files.Get "indy/genesis.txn" | toYaml | nindent 10}}