apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-apiserver-config
  labels:
    app: {{ include "canis.fullname" . }}-canis-apiserver
data:
  canis-apiserver-config.yaml: |-
    ###############################################################
    #
    #  API Server
    #
    ###############################################################
    api:
      grpc:
        host: 0.0.0.0
        port: {{ .Values.apiserver.grpc.port }}
      grpcBridge:
        host: 0.0.0.0
        port: {{ .Values.apiserver.grpcBridge.port }}
    
    ###############################################################
    #
    #  Doorman configuration
    #
    ###############################################################
    doorman:
      grpc:
        host: canis-didcomm-doorman
        port: {{ .Values.doorman.grpc.port }}
    
    ###############################################################
    #
    #  Issuer configuration
    #
    ###############################################################
    issuer:
      grpc:
        host: canis-didcomm-issuer
        port: {{ .Values.issuer.grpc.port }}

    ###############################################################
    #
    #  Verifier configuration
    #
    ###############################################################
    verifier:
      grpc:
        host: canis-didcomm-verifier
        port: {{ .Values.verifier.grpc.port }}
    
    ###############################################################
    #
    #  Loadbalancer configuration
    #
    ###############################################################
    loadbalancer:
      grpc:
        host: canis-didcomm-lb
        port: {{ .Values.loadbalancer.grpc.port }}
