apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-apiserver-config
  labels:
    app: {{ include "canis.fullname" . }}-canis-apiserver
data:
  canis-apiserver-config.yaml: |-
    ###############################################################
    #
    #  Datastore configuration
    #
    ###############################################################
    datastore:
      {{- toYaml .Values.datastore | nindent 6 }}

    ###############################################################
    #
    #  Ledger-store configuration
    #
    ###############################################################
    ledgerstore:
      {{- toYaml .Values.ledgerstore | nindent 6 }}

    ###############################################################
    #
    #  Wallet configuration
    #
    ###############################################################
    wallet:
      masterLockKey: "OTsonzgWMNAqR24bgGcZVHVBB_oqLoXntW4s_vCs6uQ="
    
    ###############################################################
    #
    #  API Server
    #
    ###############################################################
    api:
      grpc:
        host: 0.0.0.0
        port: 7778
      grpcBridge:
        host: 0.0.0.0
        port: 7779
    
    ###############################################################
    #
    #  Doorman configuration
    #
    ###############################################################
    doorman:
      grpc:
        host: canis-didcomm-doorman
        port: 8886
    
    ###############################################################
    #
    #  Issuer configuration
    #
    ###############################################################
    issuer:
      grpc:
        host: canis-didcomm-issuer
        port: 7776
    
    ###############################################################
    #
    #  Loadbalancer configuration
    #
    ###############################################################
    loadbalancer:
      grpc:
        host: canis-didcomm-lb
        port: 9996
    
    ###############################################################
    #
    #  Indy VDR Configuration
    #
    ###############################################################
    genesisFile: {{- .Files.Get "indy/genesis.txn" | toYaml | nindent 4}}
