apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-cloudagent
  labels:
    name: {{ include "canis.fullname" . }}-didcomm-cloudagent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "canis.fullname" . }}-didcomm-cloudagent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ include "canis.fullname" . }}-didcomm-cloudagent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          name: didcomm-cloudagent
          command:
            - canis-didcomm-cloudagent
            - start
          ports:
            - name: grpc
              containerPort: {{ .Values.cloudagent.grpc.port }}
              protocol: TCP
            - name: grpcbridge
              containerPort: {{ .Values.cloudagent.grpcBridge.port }}
              protocol: TCP
            - name: ws-didcomm
              containerPort: {{ .Values.cloudagent.inbound.wsPort }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: "/etc/canis"
              name: didcomm-cloudagent-config
            - mountPath: "/etc/canis/common"
              name: common-config
      restartPolicy: Always
      volumes:
        - name: didcomm-cloudagent-config
          configMap:
            name: {{ include "canis.fullname" . }}-didcomm-cloudagent-config
        - name: common-config
          configMap:
            name: {{ include "canis.fullname" . }}-common-config
