{{ if ne .Values.loadbalancerIP "" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: canis-didcomm-lb-external
  name: canis-didcomm-lb-external
spec:
  ports:
    - name: ws-didcomm
      port: 9001
      protocol: TCP
      targetPort: 9001
    - name: http-didcomm
      port: 9003
      protocol: TCP
      targetPort: 9003
  selector:
    name: canis-didcomm-lb
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadbalancerIP }}
{{ else }}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: canis-didcomm-lb-external
  name: canis-didcomm-lb-external
spec:
  ports:
    - name: ws-didcomm
      port: 9001
      protocol: TCP
      targetPort: 9001
      nodePort: 30001
    - name: http-didcomm
      port: 9003
      protocol: TCP
      targetPort: 9003
      nodePort: 30003
  selector:
    name: canis-didcomm-lb
  sessionAffinity: None
  type: NodePort
{{ end }}