apiVersion: v1
kind: Service
metadata:
  labels:
    name: canis-didcomm-issuer
  name: canis-didcomm-issuer
spec:
  ports:
    - name: grpc
      port: 7776
      protocol: TCP
      targetPort: 7776
  selector:
    name: canis-didcomm-issuer
  sessionAffinity: None
  type: ClusterIP
