apiVersion: v1
kind: Service
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-lb
  labels:
    name: {{ include "canis.fullname" . }}-didcomm-lb
spec:
  ports:
    - name: grpc
      port: {{ .Values.loadbalancer.grpc.port }}
      protocol: TCP
      targetPort: {{ .Values.loadbalancer.grpc.port }}
  selector:
    name: {{ include "canis.fullname" . }}-didcomm-lb
  sessionAffinity: None
  type: ClusterIP
