apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-doorman-config
  labels:
    app: {{ include "canis.fullname" . }}-didcomm-doorman
data:
  canis-doorman-config.yaml: |-
    ###############################################################
    #
    #  DIDComm Server
    #
    ###############################################################
    api:
      grpc:
        host: 0.0.0.0
        port: {{ .Values.doorman.grpc.port }}
    inbound:
      external: "ws://{{ .Values.loadbalancer.inbound.external.host }}:{{if ne .Values.loadbalancerIP ""}}{{ .Values.loadbalancer.inbound.wsPort }}{{ else }}{{ .Values.loadbalancer.inbound.external.wsPort }}{{end}}"
      amqp:
        {{- toYaml .Values.amqp | nindent 8 }}

    ###############################################################
    #
    #  Datastore configuration
    #
    ###############################################################
    datastore:
      {{- toYaml .Values.datastore | nindent 6 }}

    ###############################################################
    #
    #  Ledger-store configuration
    #
    ###############################################################
    ledgerstore:
      {{- toYaml .Values.ledgerstore | nindent 6 }}

    ###############################################################
    #
    #  Aries Indy VDRI Configuration
    #
    ###############################################################
    aries:
      vdri:
        - type: indy
          method: "scr"
          genesisFile: {{- .Files.Get "indy/genesis.txn" | toYaml | nindent 10}}

