apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-mediator-config
  labels:
    app: {{ include "canis.fullname" . }}-didcomm-mediator
data:
  canis-mediator-config.yaml: |-
    ###############################################################
    #
    #  DIDComm Mediator
    #
    ###############################################################
    inbound:
      host: 0.0.0.0
      httpPort: {{ .Values.mediator.inbound.httpPort }}
      wsPort: {{ .Values.mediator.inbound.wsPort }}
      {{if eq .Values.mediator.external.type "loadbalancer"}}
      external: "ws://{{ .Values.mediator.external.loadbalancer.host}}:{{ .Values.mediator.inbound.wsPort }}"
      {{ else }}
      external: "ws://{{ .Values.mediator.external.nodePort.host }}:{{ .Values.mediator.external.nodePort.wsPort }}"
      {{ end }}

    ###############################################################
    #
    #  GRPC Server
    #
    ###############################################################
    mediator:
      grpc:
        host: 0.0.0.0
        port: {{ .Values.mediator.grpc.port }}
      edgeAgentSecret: {{ .Values.mediator.secret }}