apiVersion: v1
kind: Service
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-issuer
  labels:
    name: {{ include "canis.fullname" . }}-didcomm-issuer
spec:
  ports:
    - name: grpc
      port: 7776
      protocol: TCP
      targetPort: 7776
  selector:
    name: {{ include "canis.fullname" . }}-didcomm-issuer
  sessionAffinity: None
  type: ClusterIP
