apiVersion: v1
kind: Service
metadata:
  labels:
    name: canis-didcomm-lb
  name: canis-didcomm-lb
spec:
  ports:
    - name: grpc
      port: 9996
      protocol: TCP
      targetPort: 9996
  selector:
    name: canis-didcomm-lb
  sessionAffinity: None
  type: ClusterIP
