apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-verifier-config
  labels:
    app: {{ include "canis.fullname" . }}-didcomm-verifier
data:
  canis-verifier-config.yaml: |-
    ###############################################################
    #
    #  DIDComm Server
    #
    ###############################################################
    api:
      grpc:
        host: 0.0.0.0
        port: {{ .Values.verifier.grpc.port }}
    inbound:
      external: ws://0.0.0.0:3001
      amqp:
        {{- toYaml .Values.amqp | nindent 8 }}
