apiVersion: v1
kind: Service
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-doorman
  labels:
    name: {{ include "canis.fullname" . }}-didcomm-doorman
spec:
  ports:
    - name: grpc
      port: 8886
      protocol: TCP
      targetPort: 8886
  selector:
    name: {{ include "canis.fullname" . }}-didcomm-doorman
  sessionAffinity: None
  type: ClusterIP
