apiVersion: v1
kind: Service
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-lb
  labels:
    name: {{ include "canis.fullname" . }}-didcomm-lb
spec:
  ports:
    - name: grpc
      port: 9996
      protocol: TCP
      targetPort: 9996
  selector:
    name: {{ include "canis.fullname" . }}-didcomm-lb
  sessionAffinity: None
  type: ClusterIP
