apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-doorman-config
  labels:
    app: {{ include "canis.fullname" . }}-didcomm-doorman
data:
  canis-doorman-config.yaml: |-
    ###############################################################
    #
    #  DIDComm Server
    #
    ###############################################################
    api:
      grpc:
        host: 0.0.0.0
        port: {{ .Values.doorman.grpc.port }}
    inbound:
      {{if eq .Values.loadbalancer.external.type "loadbalancer"}}
      external: "ws://{{ .Values.loadbalancer.external.loadbalancer.host}}:{{ .Values.loadbalancer.inbound.wsPort }}"
      {{ else }}
      external: "ws://{{ .Values.loadbalancer.external.nodePort.host }}:{{ .Values.loadbalancer.external.nodePort.wsPort }}"
      {{ end }}
      amqp:
        {{- toYaml .Values.amqp | nindent 8 }}

