apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-doorman-config
  labels:
    app: {{ include "canis.fullname" . }}-didcomm-doorman
data:
  canis-doorman-config.yaml: |-
    ###############################################################
    #
    #  DIDComm Server
    #
    ###############################################################
    api:
      grpc:
        host: 0.0.0.0
        port: 8886
    inbound:
      external: ws://172.16.1.1:9001
      amqp:
        user: canis
        password: canis
        host: 172.16.1.1
        port: 5672
        vhost: canis

    ###############################################################
    #
    #  Datastore configuration
    #
    ###############################################################
    datastore:
      {{- toYaml .Values.datastore | nindent 6 }}

    ###############################################################
    #
    #  Ledger-store configuration
    #
    ###############################################################
    ledgerstore:
      {{- toYaml .Values.ledgerstore | nindent 6 }}

    ###############################################################
    #
    #  Aries Indy VDRI Configuration
    #
    ###############################################################
    aries:
      vdri:
        - type: indy
          method: "scr"
          genesisFile: {{- .Files.Get "indy/genesis.txn" | toYaml | nindent 10}}

