apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-webhook-notifier-config
  labels:
    app: {{ include "canis.fullname" . }}-webhook-notifier
data:
  canis-webhook-notifier-config.yaml: |-
    ###############################################################
    #
    #  Datastore configuration
    #
    ###############################################################
    datastore:
      {{- toYaml .Values.datastore | nindent 6 }}

    ###############################################################
    #
    #  AMQP Server (rabbitMQ)
    #
    ###############################################################
    amqp:
      {{- toYaml .Values.amqp | nindent 6 }}
