apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canis.fullname" . }}-webhook-notifier
  labels:
    name: {{ include "canis.fullname" . }}-webhook-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "canis.fullname" . }}-webhook-notifier
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ include "canis.fullname" . }}-webhook-notifier
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          name: webhook-notifier
          command:
            - canis-webhook-notifier
            - start
          resources: {}
          volumeMounts:
            - mountPath: "/etc/canis"
              name: webhook-notifier-config
            - mountPath: "/etc/canis/common"
              name: common-config
      restartPolicy: Always
      volumes:
        - name: webhook-notifier-config
          configMap:
            name: {{ include "canis.fullname" . }}-webhook-notifier-config
        - name: common-config
          configMap:
            name: {{ include "canis.fullname" . }}-common-config
