apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-webhook-notifier-config
  labels:
    app: {{ include "canis.fullname" . }}-webhook-notifier
data:
  canis-webhook-notifier.yaml: |-
    ###############################################################
    #
    #  Webhook Notifier
    #
    ###############################################################
