// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: didcomm/verifier/api/canis-didcomm-verifier.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AttrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Restrictions string               `protobuf:"bytes,2,opt,name=restrictions,proto3" json:"restrictions,omitempty"` // wql query
	NonRevoked   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=non_revoked,json=nonRevoked,proto3" json:"non_revoked,omitempty"`
}

func (x *AttrInfo) Reset() {
	*x = AttrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrInfo) ProtoMessage() {}

func (x *AttrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrInfo.ProtoReflect.Descriptor instead.
func (*AttrInfo) Descriptor() ([]byte, []int) {
	return file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *AttrInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttrInfo) GetRestrictions() string {
	if x != nil {
		return x.Restrictions
	}
	return ""
}

func (x *AttrInfo) GetNonRevoked() *timestamp.Timestamp {
	if x != nil {
		return x.NonRevoked
	}
	return nil
}

type PredicateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                // attribute name, (case insensitive and ignore spaces)
	PType        string               `protobuf:"bytes,2,opt,name=p_type,json=pType,proto3" json:"p_type,omitempty"` // (Currently >= only)
	PValue       string               `protobuf:"bytes,3,opt,name=p_value,json=pValue,proto3" json:"p_value,omitempty"`
	Restrictions string               `protobuf:"bytes,4,opt,name=restrictions,proto3" json:"restrictions,omitempty"` // wql query
	NonRevoked   *timestamp.Timestamp `protobuf:"bytes,5,opt,name=non_revoked,json=nonRevoked,proto3" json:"non_revoked,omitempty"`
}

func (x *PredicateInfo) Reset() {
	*x = PredicateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredicateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredicateInfo) ProtoMessage() {}

func (x *PredicateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredicateInfo.ProtoReflect.Descriptor instead.
func (*PredicateInfo) Descriptor() ([]byte, []int) {
	return file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescGZIP(), []int{1}
}

func (x *PredicateInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PredicateInfo) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *PredicateInfo) GetPValue() string {
	if x != nil {
		return x.PValue
	}
	return ""
}

func (x *PredicateInfo) GetRestrictions() string {
	if x != nil {
		return x.Restrictions
	}
	return ""
}

func (x *PredicateInfo) GetNonRevoked() *timestamp.Timestamp {
	if x != nil {
		return x.NonRevoked
	}
	return nil
}

type RequestPresentationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId             string                    `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ExternalId          string                    `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	SchemaId            string                    `protobuf:"bytes,3,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Comment             string                    `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Type                string                    `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	WillConfirm         bool                      `protobuf:"varint,6,opt,name=will_confirm,json=willConfirm,proto3" json:"will_confirm,omitempty"`
	RequestedAttributes map[string]*AttrInfo      `protobuf:"bytes,7,rep,name=requested_attributes,json=requestedAttributes,proto3" json:"requested_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RequestedPredicates map[string]*PredicateInfo `protobuf:"bytes,8,rep,name=requested_predicates,json=requestedPredicates,proto3" json:"requested_predicates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RequestPresentationRequest) Reset() {
	*x = RequestPresentationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPresentationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPresentationRequest) ProtoMessage() {}

func (x *RequestPresentationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPresentationRequest.ProtoReflect.Descriptor instead.
func (*RequestPresentationRequest) Descriptor() ([]byte, []int) {
	return file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescGZIP(), []int{2}
}

func (x *RequestPresentationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RequestPresentationRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *RequestPresentationRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *RequestPresentationRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RequestPresentationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RequestPresentationRequest) GetWillConfirm() bool {
	if x != nil {
		return x.WillConfirm
	}
	return false
}

func (x *RequestPresentationRequest) GetRequestedAttributes() map[string]*AttrInfo {
	if x != nil {
		return x.RequestedAttributes
	}
	return nil
}

func (x *RequestPresentationRequest) GetRequestedPredicates() map[string]*PredicateInfo {
	if x != nil {
		return x.RequestedPredicates
	}
	return nil
}

type RequestPresentationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestPresentationId string `protobuf:"bytes,1,opt,name=request_presentation_id,json=requestPresentationId,proto3" json:"request_presentation_id,omitempty"`
}

func (x *RequestPresentationResponse) Reset() {
	*x = RequestPresentationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPresentationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPresentationResponse) ProtoMessage() {}

func (x *RequestPresentationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPresentationResponse.ProtoReflect.Descriptor instead.
func (*RequestPresentationResponse) Descriptor() ([]byte, []int) {
	return file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescGZIP(), []int{3}
}

func (x *RequestPresentationResponse) GetRequestPresentationId() string {
	if x != nil {
		return x.RequestPresentationId
	}
	return ""
}

var File_didcomm_verifier_api_canis_didcomm_verifier_proto protoreflect.FileDescriptor

var file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDesc = []byte{
	0x0a, 0x31, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x6e, 0x69, 0x73, 0x2d, 0x64, 0x69, 0x64,
	0x63, 0x6f, 0x6d, 0x6d, 0x2d, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a,
	0x08, 0x41, 0x74, 0x74, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x6e, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0a, 0x6e, 0x6f, 0x6e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x22, 0xb4,
	0x01, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x6e, 0x6f, 0x6e, 0x5f,
	0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x6e, 0x6f, 0x6e, 0x52, 0x65,
	0x76, 0x6f, 0x6b, 0x65, 0x64, 0x22, 0xe3, 0x04, 0x0a, 0x1a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x77,
	0x69, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x77, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x6f,
	0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x64,
	0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x13, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12,
	0x6f, 0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e,
	0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x13, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73,
	0x1a, 0x59, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x5e, 0x0a, 0x18, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x64, 0x63, 0x6f,
	0x6d, 0x6d, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x55, 0x0a, 0x1b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x32, 0x6e, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x62,
	0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x69, 0x64,
	0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescOnce sync.Once
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescData = file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDesc
)

func file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescGZIP() []byte {
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescOnce.Do(func() {
		file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescData)
	})
	return file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescData
}

var file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_didcomm_verifier_api_canis_didcomm_verifier_proto_goTypes = []interface{}{
	(*AttrInfo)(nil),                    // 0: didcomm.AttrInfo
	(*PredicateInfo)(nil),               // 1: didcomm.PredicateInfo
	(*RequestPresentationRequest)(nil),  // 2: didcomm.RequestPresentationRequest
	(*RequestPresentationResponse)(nil), // 3: didcomm.RequestPresentationResponse
	nil,                                 // 4: didcomm.RequestPresentationRequest.RequestedAttributesEntry
	nil,                                 // 5: didcomm.RequestPresentationRequest.RequestedPredicatesEntry
	(*timestamp.Timestamp)(nil),         // 6: google.protobuf.Timestamp
}
var file_didcomm_verifier_api_canis_didcomm_verifier_proto_depIdxs = []int32{
	6, // 0: didcomm.AttrInfo.non_revoked:type_name -> google.protobuf.Timestamp
	6, // 1: didcomm.PredicateInfo.non_revoked:type_name -> google.protobuf.Timestamp
	4, // 2: didcomm.RequestPresentationRequest.requested_attributes:type_name -> didcomm.RequestPresentationRequest.RequestedAttributesEntry
	5, // 3: didcomm.RequestPresentationRequest.requested_predicates:type_name -> didcomm.RequestPresentationRequest.RequestedPredicatesEntry
	0, // 4: didcomm.RequestPresentationRequest.RequestedAttributesEntry.value:type_name -> didcomm.AttrInfo
	1, // 5: didcomm.RequestPresentationRequest.RequestedPredicatesEntry.value:type_name -> didcomm.PredicateInfo
	2, // 6: didcomm.Verifier.RequestPresentation:input_type -> didcomm.RequestPresentationRequest
	3, // 7: didcomm.Verifier.RequestPresentation:output_type -> didcomm.RequestPresentationResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_didcomm_verifier_api_canis_didcomm_verifier_proto_init() }
func file_didcomm_verifier_api_canis_didcomm_verifier_proto_init() {
	if File_didcomm_verifier_api_canis_didcomm_verifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredicateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPresentationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPresentationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_didcomm_verifier_api_canis_didcomm_verifier_proto_goTypes,
		DependencyIndexes: file_didcomm_verifier_api_canis_didcomm_verifier_proto_depIdxs,
		MessageInfos:      file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes,
	}.Build()
	File_didcomm_verifier_api_canis_didcomm_verifier_proto = out.File
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDesc = nil
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_goTypes = nil
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VerifierClient is the client API for Verifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifierClient interface {
	RequestPresentation(ctx context.Context, in *RequestPresentationRequest, opts ...grpc.CallOption) (*RequestPresentationResponse, error)
}

type verifierClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierClient(cc grpc.ClientConnInterface) VerifierClient {
	return &verifierClient{cc}
}

func (c *verifierClient) RequestPresentation(ctx context.Context, in *RequestPresentationRequest, opts ...grpc.CallOption) (*RequestPresentationResponse, error) {
	out := new(RequestPresentationResponse)
	err := c.cc.Invoke(ctx, "/didcomm.Verifier/RequestPresentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServer is the server API for Verifier service.
type VerifierServer interface {
	RequestPresentation(context.Context, *RequestPresentationRequest) (*RequestPresentationResponse, error)
}

// UnimplementedVerifierServer can be embedded to have forward compatible implementations.
type UnimplementedVerifierServer struct {
}

func (*UnimplementedVerifierServer) RequestPresentation(context.Context, *RequestPresentationRequest) (*RequestPresentationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPresentation not implemented")
}

func RegisterVerifierServer(s *grpc.Server, srv VerifierServer) {
	s.RegisterService(&_Verifier_serviceDesc, srv)
}

func _Verifier_RequestPresentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPresentationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).RequestPresentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.Verifier/RequestPresentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).RequestPresentation(ctx, req.(*RequestPresentationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Verifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didcomm.Verifier",
	HandlerType: (*VerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPresentation",
			Handler:    _Verifier_RequestPresentation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "didcomm/verifier/api/canis-didcomm-verifier.proto",
}
