// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.12.4
// source: didcomm/verifier/api/canis-didcomm-verifier.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestPresentationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestPresentationRequest) Reset() {
	*x = RequestPresentationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPresentationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPresentationRequest) ProtoMessage() {}

func (x *RequestPresentationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPresentationRequest.ProtoReflect.Descriptor instead.
func (*RequestPresentationRequest) Descriptor() ([]byte, []int) {
	return file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescGZIP(), []int{0}
}

type RequestPresentationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestPresentationResponse) Reset() {
	*x = RequestPresentationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPresentationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPresentationResponse) ProtoMessage() {}

func (x *RequestPresentationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPresentationResponse.ProtoReflect.Descriptor instead.
func (*RequestPresentationResponse) Descriptor() ([]byte, []int) {
	return file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescGZIP(), []int{1}
}

var File_didcomm_verifier_api_canis_didcomm_verifier_proto protoreflect.FileDescriptor

var file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDesc = []byte{
	0x0a, 0x31, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x6e, 0x69, 0x73, 0x2d, 0x64, 0x69, 0x64,
	0x63, 0x6f, 0x6d, 0x6d, 0x2d, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x22, 0x1c, 0x0a, 0x1a,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6e, 0x0a, 0x08, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x62, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x64,
	0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x64, 0x69, 0x64,
	0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescOnce sync.Once
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescData = file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDesc
)

func file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescGZIP() []byte {
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescOnce.Do(func() {
		file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescData)
	})
	return file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDescData
}

var file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_didcomm_verifier_api_canis_didcomm_verifier_proto_goTypes = []interface{}{
	(*RequestPresentationRequest)(nil),  // 0: didcomm.RequestPresentationRequest
	(*RequestPresentationResponse)(nil), // 1: didcomm.RequestPresentationResponse
}
var file_didcomm_verifier_api_canis_didcomm_verifier_proto_depIdxs = []int32{
	0, // 0: didcomm.Verifier.RequestPresentation:input_type -> didcomm.RequestPresentationRequest
	1, // 1: didcomm.Verifier.RequestPresentation:output_type -> didcomm.RequestPresentationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_didcomm_verifier_api_canis_didcomm_verifier_proto_init() }
func file_didcomm_verifier_api_canis_didcomm_verifier_proto_init() {
	if File_didcomm_verifier_api_canis_didcomm_verifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPresentationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPresentationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_didcomm_verifier_api_canis_didcomm_verifier_proto_goTypes,
		DependencyIndexes: file_didcomm_verifier_api_canis_didcomm_verifier_proto_depIdxs,
		MessageInfos:      file_didcomm_verifier_api_canis_didcomm_verifier_proto_msgTypes,
	}.Build()
	File_didcomm_verifier_api_canis_didcomm_verifier_proto = out.File
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_rawDesc = nil
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_goTypes = nil
	file_didcomm_verifier_api_canis_didcomm_verifier_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VerifierClient is the client API for Verifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifierClient interface {
	RequestPresentation(ctx context.Context, in *RequestPresentationRequest, opts ...grpc.CallOption) (*RequestPresentationResponse, error)
}

type verifierClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierClient(cc grpc.ClientConnInterface) VerifierClient {
	return &verifierClient{cc}
}

func (c *verifierClient) RequestPresentation(ctx context.Context, in *RequestPresentationRequest, opts ...grpc.CallOption) (*RequestPresentationResponse, error) {
	out := new(RequestPresentationResponse)
	err := c.cc.Invoke(ctx, "/didcomm.Verifier/RequestPresentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServer is the server API for Verifier service.
type VerifierServer interface {
	RequestPresentation(context.Context, *RequestPresentationRequest) (*RequestPresentationResponse, error)
}

// UnimplementedVerifierServer can be embedded to have forward compatible implementations.
type UnimplementedVerifierServer struct {
}

func (*UnimplementedVerifierServer) RequestPresentation(context.Context, *RequestPresentationRequest) (*RequestPresentationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPresentation not implemented")
}

func RegisterVerifierServer(s *grpc.Server, srv VerifierServer) {
	s.RegisterService(&_Verifier_serviceDesc, srv)
}

func _Verifier_RequestPresentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPresentationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).RequestPresentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.Verifier/RequestPresentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).RequestPresentation(ctx, req.(*RequestPresentationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Verifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didcomm.Verifier",
	HandlerType: (*VerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPresentation",
			Handler:    _Verifier_RequestPresentation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "didcomm/verifier/api/canis-didcomm-verifier.proto",
}
