// Code generated by mockery v1.0.0. DO NOT EDIT.

package indy

import (
	"github.com/scoir/canis/pkg/credential/engine/indy"
	datastore "github.com/scoir/canis/pkg/datastore"
	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

// IndyVDR provides a mock function with given fields:
func (_m *MockProvider) IndyVDR() (indy.VDRClient, error) {
	ret := _m.Called()

	var r0 indy.VDRClient
	if rf, ok := ret.Get(0).(func() indy.VDRClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(indy.VDRClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Oracle provides a mock function with given fields:
func (_m *MockProvider) Oracle() indy.Oracle {
	ret := _m.Called()

	var r0 indy.Oracle
	if rf, ok := ret.Get(0).(func() indy.Oracle); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(indy.Oracle)
		}
	}

	return r0
}

// Store provides a mock function with given fields:
func (_m *MockProvider) Store() datastore.Store {
	ret := _m.Called()

	var r0 datastore.Store
	if rf, ok := ret.Get(0).(func() datastore.Store); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(datastore.Store)
		}
	}

	return r0
}
