// Code generated by mockery v1.0.0. DO NOT EDIT.

package indy

import (
	vdr "github.com/hyperledger/indy-vdr/wrappers/golang/vdr"
	mock "github.com/stretchr/testify/mock"
)

// MockVDRClient is an autogenerated mock type for the VDRClient type
type MockVDRClient struct {
	mock.Mock
}

// GetCredDef provides a mock function with given fields: credDefID
func (_m *MockVDRClient) GetCredDef(credDefID string) (*vdr.ReadReply, error) {
	ret := _m.Called(credDefID)

	var r0 *vdr.ReadReply
	if rf, ok := ret.Get(0).(func(string) *vdr.ReadReply); ok {
		r0 = rf(credDefID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vdr.ReadReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(credDefID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
