// Code generated by mockery v1.0.0. DO NOT EDIT.

package issuer

import (
	engine "github.com/scoir/canis/pkg/credential/engine"
	datastore "github.com/scoir/canis/pkg/datastore"

	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

// GetCredentialEngineRegistry provides a mock function with given fields:
func (_m *MockProvider) GetCredentialEngineRegistry() (engine.CredentialRegistry, error) {
	ret := _m.Called()

	var r0 engine.CredentialRegistry
	if rf, ok := ret.Get(0).(func() engine.CredentialRegistry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(engine.CredentialRegistry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCredentialIssuer provides a mock function with given fields:
func (_m *MockProvider) GetCredentialIssuer() (CredentialIssuer, error) {
	ret := _m.Called()

	var r0 CredentialIssuer
	if rf, ok := ret.Get(0).(func() CredentialIssuer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CredentialIssuer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields:
func (_m *MockProvider) Store() datastore.Store {
	ret := _m.Called()

	var r0 datastore.Store
	if rf, ok := ret.Get(0).(func() datastore.Store); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(datastore.Store)
		}
	}

	return r0
}
