// Code generated by mockery v1.0.0. DO NOT EDIT.

package issuer

import (
	issuecredential "github.com/hyperledger/aries-framework-go/pkg/client/issuecredential"
	mock "github.com/stretchr/testify/mock"
)

// MockCredentialIssuer is an autogenerated mock type for the CredentialIssuer type
type MockCredentialIssuer struct {
	mock.Mock
}

// SendOffer provides a mock function with given fields: offer, myDID, theirDID
func (_m *MockCredentialIssuer) SendOffer(offer *issuecredential.OfferCredential, myDID string, theirDID string) (string, error) {
	ret := _m.Called(offer, myDID, theirDID)

	var r0 string
	if rf, ok := ret.Get(0).(func(*issuecredential.OfferCredential, string, string) string); ok {
		r0 = rf(offer, myDID, theirDID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*issuecredential.OfferCredential, string, string) error); ok {
		r1 = rf(offer, myDID, theirDID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
