// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	io "io"

	datastore "github.com/scoir/canis/pkg/datastore"

	mock "github.com/stretchr/testify/mock"

	runtime "github.com/scoir/canis/pkg/runtime"
)

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

// AgentPS provides a mock function with given fields:
func (_m *Executor) AgentPS() []runtime.Process {
	ret := _m.Called()

	var r0 []runtime.Process
	if rf, ok := ret.Get(0).(func() []runtime.Process); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]runtime.Process)
		}
	}

	return r0
}

// Describe provides a mock function with given fields:
func (_m *Executor) Describe() {
	_m.Called()
}

// InitSteward provides a mock function with given fields: seed, d
func (_m *Executor) InitSteward(seed string, d []byte) (string, error) {
	ret := _m.Called(seed, d)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, []byte) string); ok {
		r0 = rf(seed, d)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(seed, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LaunchAgent provides a mock function with given fields: agent
func (_m *Executor) LaunchAgent(agent *datastore.Agent) (string, error) {
	ret := _m.Called(agent)

	var r0 string
	if rf, ok := ret.Get(0).(func(*datastore.Agent) string); ok {
		r0 = rf(agent)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*datastore.Agent) error); ok {
		r1 = rf(agent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LaunchSteward provides a mock function with given fields: _a0
func (_m *Executor) LaunchSteward(_a0 []byte) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PS provides a mock function with given fields:
func (_m *Executor) PS() []runtime.Process {
	ret := _m.Called()

	var r0 []runtime.Process
	if rf, ok := ret.Get(0).(func() []runtime.Process); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]runtime.Process)
		}
	}

	return r0
}

// ShutdownAgent provides a mock function with given fields: pID
func (_m *Executor) ShutdownAgent(pID string) error {
	ret := _m.Called(pID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShutdownSteward provides a mock function with given fields:
func (_m *Executor) ShutdownSteward() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Status provides a mock function with given fields: pID
func (_m *Executor) Status(pID string) (runtime.Process, error) {
	ret := _m.Called(pID)

	var r0 runtime.Process
	if rf, ok := ret.Get(0).(func(string) runtime.Process); ok {
		r0 = rf(pID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runtime.Process)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StreamLogs provides a mock function with given fields: pID
func (_m *Executor) StreamLogs(pID string) (io.ReadCloser, error) {
	ret := _m.Called(pID)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(string) io.ReadCloser); ok {
		r0 = rf(pID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: pID
func (_m *Executor) Watch(pID string) (runtime.Watcher, error) {
	ret := _m.Called(pID)

	var r0 runtime.Watcher
	if rf, ok := ret.Get(0).(func(string) runtime.Watcher); ok {
		r0 = rf(pID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runtime.Watcher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
