// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: canis-didcomm-cloudagent.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	common "github.com/scoir/canis/pkg/protogen/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_canis_didcomm_cloudagent_proto protoreflect.FileDescriptor

var file_canis_didcomm_cloudagent_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x61, 0x6e, 0x69, 0x73, 0x2d, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2d,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xff,
	0x06, 0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x74, 0x0a,
	0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x22, 0x0c, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x3a, 0x01, 0x2a, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x16, 0x50, 0x6f, 0x6c, 0x6c, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x79, 0x0a, 0x10, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1c, 0x22, 0x17, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x57, 0x0a,
	0x10, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x14, 0x50, 0x6f, 0x6c, 0x6c, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x12, 0x23,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6c,
	0x6c, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x10, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12,
	0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x74, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a,
	0x22, 0x18, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x54, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x1e, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x18, 0x5a, 0x16, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var file_canis_didcomm_cloudagent_proto_goTypes = []interface{}{
	(*common.RegisterCloudAgentRequest)(nil),    // 0: common.RegisterCloudAgentRequest
	(*common.EndpointRequest)(nil),              // 1: common.EndpointRequest
	(*common.PollConnectionRequest)(nil),        // 2: common.PollConnectionRequest
	(*common.HandleInvitationRequest)(nil),      // 3: common.HandleInvitationRequest
	(*common.AcceptConnectionRequest)(nil),      // 4: common.AcceptConnectionRequest
	(*common.PollCredentialOffersRequest)(nil),  // 5: common.PollCredentialOffersRequest
	(*common.AcceptCredentialRequest)(nil),      // 6: common.AcceptCredentialRequest
	(*common.ListConnectionsRequest)(nil),       // 7: common.ListConnectionsRequest
	(*common.ListCredentialsRequest)(nil),       // 8: common.ListCredentialsRequest
	(*common.RegisterCloudAgentResponse)(nil),   // 9: common.RegisterCloudAgentResponse
	(*common.EndpointResponse)(nil),             // 10: common.EndpointResponse
	(*common.PollConnectionResponse)(nil),       // 11: common.PollConnectionResponse
	(*common.HandleInvitationResponse)(nil),     // 12: common.HandleInvitationResponse
	(*common.AcceptConnectionResponse)(nil),     // 13: common.AcceptConnectionResponse
	(*common.PollCredentialOffersResponse)(nil), // 14: common.PollCredentialOffersResponse
	(*common.AcceptCredentialResponse)(nil),     // 15: common.AcceptCredentialResponse
	(*common.ListConnectionsResponse)(nil),      // 16: common.ListConnectionsResponse
	(*common.ListCredentialsResponse)(nil),      // 17: common.ListCredentialsResponse
}
var file_canis_didcomm_cloudagent_proto_depIdxs = []int32{
	0,  // 0: didcomm.CloudAgent.RegisterCloudAgent:input_type -> common.RegisterCloudAgentRequest
	1,  // 1: didcomm.CloudAgent.GetEndpoint:input_type -> common.EndpointRequest
	2,  // 2: didcomm.CloudAgent.PollConnectionRequests:input_type -> common.PollConnectionRequest
	3,  // 3: didcomm.CloudAgent.HandleInvitation:input_type -> common.HandleInvitationRequest
	4,  // 4: didcomm.CloudAgent.AcceptConnection:input_type -> common.AcceptConnectionRequest
	5,  // 5: didcomm.CloudAgent.PollCredentialOffers:input_type -> common.PollCredentialOffersRequest
	6,  // 6: didcomm.CloudAgent.AcceptCredential:input_type -> common.AcceptCredentialRequest
	7,  // 7: didcomm.CloudAgent.ListConnections:input_type -> common.ListConnectionsRequest
	8,  // 8: didcomm.CloudAgent.ListCredentials:input_type -> common.ListCredentialsRequest
	9,  // 9: didcomm.CloudAgent.RegisterCloudAgent:output_type -> common.RegisterCloudAgentResponse
	10, // 10: didcomm.CloudAgent.GetEndpoint:output_type -> common.EndpointResponse
	11, // 11: didcomm.CloudAgent.PollConnectionRequests:output_type -> common.PollConnectionResponse
	12, // 12: didcomm.CloudAgent.HandleInvitation:output_type -> common.HandleInvitationResponse
	13, // 13: didcomm.CloudAgent.AcceptConnection:output_type -> common.AcceptConnectionResponse
	14, // 14: didcomm.CloudAgent.PollCredentialOffers:output_type -> common.PollCredentialOffersResponse
	15, // 15: didcomm.CloudAgent.AcceptCredential:output_type -> common.AcceptCredentialResponse
	16, // 16: didcomm.CloudAgent.ListConnections:output_type -> common.ListConnectionsResponse
	17, // 17: didcomm.CloudAgent.ListCredentials:output_type -> common.ListCredentialsResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_canis_didcomm_cloudagent_proto_init() }
func file_canis_didcomm_cloudagent_proto_init() {
	if File_canis_didcomm_cloudagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_canis_didcomm_cloudagent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_canis_didcomm_cloudagent_proto_goTypes,
		DependencyIndexes: file_canis_didcomm_cloudagent_proto_depIdxs,
	}.Build()
	File_canis_didcomm_cloudagent_proto = out.File
	file_canis_didcomm_cloudagent_proto_rawDesc = nil
	file_canis_didcomm_cloudagent_proto_goTypes = nil
	file_canis_didcomm_cloudagent_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CloudAgentClient is the client API for CloudAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudAgentClient interface {
	RegisterCloudAgent(ctx context.Context, in *common.RegisterCloudAgentRequest, opts ...grpc.CallOption) (*common.RegisterCloudAgentResponse, error)
	GetEndpoint(ctx context.Context, in *common.EndpointRequest, opts ...grpc.CallOption) (*common.EndpointResponse, error)
	PollConnectionRequests(ctx context.Context, in *common.PollConnectionRequest, opts ...grpc.CallOption) (*common.PollConnectionResponse, error)
	HandleInvitation(ctx context.Context, in *common.HandleInvitationRequest, opts ...grpc.CallOption) (*common.HandleInvitationResponse, error)
	AcceptConnection(ctx context.Context, in *common.AcceptConnectionRequest, opts ...grpc.CallOption) (*common.AcceptConnectionResponse, error)
	PollCredentialOffers(ctx context.Context, in *common.PollCredentialOffersRequest, opts ...grpc.CallOption) (*common.PollCredentialOffersResponse, error)
	AcceptCredential(ctx context.Context, in *common.AcceptCredentialRequest, opts ...grpc.CallOption) (*common.AcceptCredentialResponse, error)
	ListConnections(ctx context.Context, in *common.ListConnectionsRequest, opts ...grpc.CallOption) (*common.ListConnectionsResponse, error)
	ListCredentials(ctx context.Context, in *common.ListCredentialsRequest, opts ...grpc.CallOption) (*common.ListCredentialsResponse, error)
}

type cloudAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudAgentClient(cc grpc.ClientConnInterface) CloudAgentClient {
	return &cloudAgentClient{cc}
}

func (c *cloudAgentClient) RegisterCloudAgent(ctx context.Context, in *common.RegisterCloudAgentRequest, opts ...grpc.CallOption) (*common.RegisterCloudAgentResponse, error) {
	out := new(common.RegisterCloudAgentResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/RegisterCloudAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) GetEndpoint(ctx context.Context, in *common.EndpointRequest, opts ...grpc.CallOption) (*common.EndpointResponse, error) {
	out := new(common.EndpointResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/GetEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) PollConnectionRequests(ctx context.Context, in *common.PollConnectionRequest, opts ...grpc.CallOption) (*common.PollConnectionResponse, error) {
	out := new(common.PollConnectionResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/PollConnectionRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) HandleInvitation(ctx context.Context, in *common.HandleInvitationRequest, opts ...grpc.CallOption) (*common.HandleInvitationResponse, error) {
	out := new(common.HandleInvitationResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/HandleInvitation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) AcceptConnection(ctx context.Context, in *common.AcceptConnectionRequest, opts ...grpc.CallOption) (*common.AcceptConnectionResponse, error) {
	out := new(common.AcceptConnectionResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/AcceptConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) PollCredentialOffers(ctx context.Context, in *common.PollCredentialOffersRequest, opts ...grpc.CallOption) (*common.PollCredentialOffersResponse, error) {
	out := new(common.PollCredentialOffersResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/PollCredentialOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) AcceptCredential(ctx context.Context, in *common.AcceptCredentialRequest, opts ...grpc.CallOption) (*common.AcceptCredentialResponse, error) {
	out := new(common.AcceptCredentialResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/AcceptCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) ListConnections(ctx context.Context, in *common.ListConnectionsRequest, opts ...grpc.CallOption) (*common.ListConnectionsResponse, error) {
	out := new(common.ListConnectionsResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/ListConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) ListCredentials(ctx context.Context, in *common.ListCredentialsRequest, opts ...grpc.CallOption) (*common.ListCredentialsResponse, error) {
	out := new(common.ListCredentialsResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/ListCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudAgentServer is the server API for CloudAgent service.
type CloudAgentServer interface {
	RegisterCloudAgent(context.Context, *common.RegisterCloudAgentRequest) (*common.RegisterCloudAgentResponse, error)
	GetEndpoint(context.Context, *common.EndpointRequest) (*common.EndpointResponse, error)
	PollConnectionRequests(context.Context, *common.PollConnectionRequest) (*common.PollConnectionResponse, error)
	HandleInvitation(context.Context, *common.HandleInvitationRequest) (*common.HandleInvitationResponse, error)
	AcceptConnection(context.Context, *common.AcceptConnectionRequest) (*common.AcceptConnectionResponse, error)
	PollCredentialOffers(context.Context, *common.PollCredentialOffersRequest) (*common.PollCredentialOffersResponse, error)
	AcceptCredential(context.Context, *common.AcceptCredentialRequest) (*common.AcceptCredentialResponse, error)
	ListConnections(context.Context, *common.ListConnectionsRequest) (*common.ListConnectionsResponse, error)
	ListCredentials(context.Context, *common.ListCredentialsRequest) (*common.ListCredentialsResponse, error)
}

// UnimplementedCloudAgentServer can be embedded to have forward compatible implementations.
type UnimplementedCloudAgentServer struct {
}

func (*UnimplementedCloudAgentServer) RegisterCloudAgent(context.Context, *common.RegisterCloudAgentRequest) (*common.RegisterCloudAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCloudAgent not implemented")
}
func (*UnimplementedCloudAgentServer) GetEndpoint(context.Context, *common.EndpointRequest) (*common.EndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEndpoint not implemented")
}
func (*UnimplementedCloudAgentServer) PollConnectionRequests(context.Context, *common.PollConnectionRequest) (*common.PollConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollConnectionRequests not implemented")
}
func (*UnimplementedCloudAgentServer) HandleInvitation(context.Context, *common.HandleInvitationRequest) (*common.HandleInvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleInvitation not implemented")
}
func (*UnimplementedCloudAgentServer) AcceptConnection(context.Context, *common.AcceptConnectionRequest) (*common.AcceptConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptConnection not implemented")
}
func (*UnimplementedCloudAgentServer) PollCredentialOffers(context.Context, *common.PollCredentialOffersRequest) (*common.PollCredentialOffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollCredentialOffers not implemented")
}
func (*UnimplementedCloudAgentServer) AcceptCredential(context.Context, *common.AcceptCredentialRequest) (*common.AcceptCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptCredential not implemented")
}
func (*UnimplementedCloudAgentServer) ListConnections(context.Context, *common.ListConnectionsRequest) (*common.ListConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (*UnimplementedCloudAgentServer) ListCredentials(context.Context, *common.ListCredentialsRequest) (*common.ListCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCredentials not implemented")
}

func RegisterCloudAgentServer(s *grpc.Server, srv CloudAgentServer) {
	s.RegisterService(&_CloudAgent_serviceDesc, srv)
}

func _CloudAgent_RegisterCloudAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.RegisterCloudAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).RegisterCloudAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/RegisterCloudAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).RegisterCloudAgent(ctx, req.(*common.RegisterCloudAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_GetEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).GetEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/GetEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).GetEndpoint(ctx, req.(*common.EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_PollConnectionRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PollConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).PollConnectionRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/PollConnectionRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).PollConnectionRequests(ctx, req.(*common.PollConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_HandleInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.HandleInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).HandleInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/HandleInvitation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).HandleInvitation(ctx, req.(*common.HandleInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_AcceptConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.AcceptConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).AcceptConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/AcceptConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).AcceptConnection(ctx, req.(*common.AcceptConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_PollCredentialOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PollCredentialOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).PollCredentialOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/PollCredentialOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).PollCredentialOffers(ctx, req.(*common.PollCredentialOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_AcceptCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.AcceptCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).AcceptCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/AcceptCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).AcceptCredential(ctx, req.(*common.AcceptCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/ListConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).ListConnections(ctx, req.(*common.ListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_ListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).ListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/ListCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).ListCredentials(ctx, req.(*common.ListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didcomm.CloudAgent",
	HandlerType: (*CloudAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCloudAgent",
			Handler:    _CloudAgent_RegisterCloudAgent_Handler,
		},
		{
			MethodName: "GetEndpoint",
			Handler:    _CloudAgent_GetEndpoint_Handler,
		},
		{
			MethodName: "PollConnectionRequests",
			Handler:    _CloudAgent_PollConnectionRequests_Handler,
		},
		{
			MethodName: "HandleInvitation",
			Handler:    _CloudAgent_HandleInvitation_Handler,
		},
		{
			MethodName: "AcceptConnection",
			Handler:    _CloudAgent_AcceptConnection_Handler,
		},
		{
			MethodName: "PollCredentialOffers",
			Handler:    _CloudAgent_PollCredentialOffers_Handler,
		},
		{
			MethodName: "AcceptCredential",
			Handler:    _CloudAgent_AcceptCredential_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _CloudAgent_ListConnections_Handler,
		},
		{
			MethodName: "ListCredentials",
			Handler:    _CloudAgent_ListCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "canis-didcomm-cloudagent.proto",
}
