// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: canis-didcomm-cloudagent.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	common "github.com/scoir/canis/pkg/protogen/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_canis_didcomm_cloudagent_proto protoreflect.FileDescriptor

var file_canis_didcomm_cloudagent_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x61, 0x6e, 0x69, 0x73, 0x2d, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2d,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x64, 0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xba,
	0x05, 0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x74, 0x0a,
	0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x22, 0x0c, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x3a, 0x01, 0x2a, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x79, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x22, 0x17, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a,
	0x01, 0x2a, 0x12, 0x8a, 0x01, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x2d, 0x22, 0x28, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2f, 0x7b, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x7d, 0x3a, 0x01, 0x2a, 0x12,
	0x74, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22, 0x18, 0x2f, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x74, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1a, 0x22, 0x18, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x64,
	0x69, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_canis_didcomm_cloudagent_proto_goTypes = []interface{}{
	(*common.RegisterCloudAgentRequest)(nil),  // 0: common.RegisterCloudAgentRequest
	(*common.EndpointRequest)(nil),            // 1: common.EndpointRequest
	(*common.HandleInvitationRequest)(nil),    // 2: common.HandleInvitationRequest
	(*common.AcceptCredentialRequest)(nil),    // 3: common.AcceptCredentialRequest
	(*common.ListConnectionsRequest)(nil),     // 4: common.ListConnectionsRequest
	(*common.ListCredentialsRequest)(nil),     // 5: common.ListCredentialsRequest
	(*common.RegisterCloudAgentResponse)(nil), // 6: common.RegisterCloudAgentResponse
	(*common.EndpointResponse)(nil),           // 7: common.EndpointResponse
	(*common.HandleInvitationResponse)(nil),   // 8: common.HandleInvitationResponse
	(*common.AcceptCredentialResponse)(nil),   // 9: common.AcceptCredentialResponse
	(*common.ListConnectionsResponse)(nil),    // 10: common.ListConnectionsResponse
	(*common.ListCredentialsResponse)(nil),    // 11: common.ListCredentialsResponse
}
var file_canis_didcomm_cloudagent_proto_depIdxs = []int32{
	0,  // 0: didcomm.CloudAgent.RegisterCloudAgent:input_type -> common.RegisterCloudAgentRequest
	1,  // 1: didcomm.CloudAgent.GetEndpoint:input_type -> common.EndpointRequest
	2,  // 2: didcomm.CloudAgent.AcceptInvitation:input_type -> common.HandleInvitationRequest
	3,  // 3: didcomm.CloudAgent.AcceptCredential:input_type -> common.AcceptCredentialRequest
	4,  // 4: didcomm.CloudAgent.ListConnections:input_type -> common.ListConnectionsRequest
	5,  // 5: didcomm.CloudAgent.ListCredentials:input_type -> common.ListCredentialsRequest
	6,  // 6: didcomm.CloudAgent.RegisterCloudAgent:output_type -> common.RegisterCloudAgentResponse
	7,  // 7: didcomm.CloudAgent.GetEndpoint:output_type -> common.EndpointResponse
	8,  // 8: didcomm.CloudAgent.AcceptInvitation:output_type -> common.HandleInvitationResponse
	9,  // 9: didcomm.CloudAgent.AcceptCredential:output_type -> common.AcceptCredentialResponse
	10, // 10: didcomm.CloudAgent.ListConnections:output_type -> common.ListConnectionsResponse
	11, // 11: didcomm.CloudAgent.ListCredentials:output_type -> common.ListCredentialsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_canis_didcomm_cloudagent_proto_init() }
func file_canis_didcomm_cloudagent_proto_init() {
	if File_canis_didcomm_cloudagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_canis_didcomm_cloudagent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_canis_didcomm_cloudagent_proto_goTypes,
		DependencyIndexes: file_canis_didcomm_cloudagent_proto_depIdxs,
	}.Build()
	File_canis_didcomm_cloudagent_proto = out.File
	file_canis_didcomm_cloudagent_proto_rawDesc = nil
	file_canis_didcomm_cloudagent_proto_goTypes = nil
	file_canis_didcomm_cloudagent_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CloudAgentClient is the client API for CloudAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudAgentClient interface {
	RegisterCloudAgent(ctx context.Context, in *common.RegisterCloudAgentRequest, opts ...grpc.CallOption) (*common.RegisterCloudAgentResponse, error)
	GetEndpoint(ctx context.Context, in *common.EndpointRequest, opts ...grpc.CallOption) (*common.EndpointResponse, error)
	AcceptInvitation(ctx context.Context, in *common.HandleInvitationRequest, opts ...grpc.CallOption) (*common.HandleInvitationResponse, error)
	AcceptCredential(ctx context.Context, in *common.AcceptCredentialRequest, opts ...grpc.CallOption) (*common.AcceptCredentialResponse, error)
	ListConnections(ctx context.Context, in *common.ListConnectionsRequest, opts ...grpc.CallOption) (*common.ListConnectionsResponse, error)
	ListCredentials(ctx context.Context, in *common.ListCredentialsRequest, opts ...grpc.CallOption) (*common.ListCredentialsResponse, error)
}

type cloudAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudAgentClient(cc grpc.ClientConnInterface) CloudAgentClient {
	return &cloudAgentClient{cc}
}

func (c *cloudAgentClient) RegisterCloudAgent(ctx context.Context, in *common.RegisterCloudAgentRequest, opts ...grpc.CallOption) (*common.RegisterCloudAgentResponse, error) {
	out := new(common.RegisterCloudAgentResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/RegisterCloudAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) GetEndpoint(ctx context.Context, in *common.EndpointRequest, opts ...grpc.CallOption) (*common.EndpointResponse, error) {
	out := new(common.EndpointResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/GetEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) AcceptInvitation(ctx context.Context, in *common.HandleInvitationRequest, opts ...grpc.CallOption) (*common.HandleInvitationResponse, error) {
	out := new(common.HandleInvitationResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/AcceptInvitation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) AcceptCredential(ctx context.Context, in *common.AcceptCredentialRequest, opts ...grpc.CallOption) (*common.AcceptCredentialResponse, error) {
	out := new(common.AcceptCredentialResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/AcceptCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) ListConnections(ctx context.Context, in *common.ListConnectionsRequest, opts ...grpc.CallOption) (*common.ListConnectionsResponse, error) {
	out := new(common.ListConnectionsResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/ListConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAgentClient) ListCredentials(ctx context.Context, in *common.ListCredentialsRequest, opts ...grpc.CallOption) (*common.ListCredentialsResponse, error) {
	out := new(common.ListCredentialsResponse)
	err := c.cc.Invoke(ctx, "/didcomm.CloudAgent/ListCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudAgentServer is the server API for CloudAgent service.
type CloudAgentServer interface {
	RegisterCloudAgent(context.Context, *common.RegisterCloudAgentRequest) (*common.RegisterCloudAgentResponse, error)
	GetEndpoint(context.Context, *common.EndpointRequest) (*common.EndpointResponse, error)
	AcceptInvitation(context.Context, *common.HandleInvitationRequest) (*common.HandleInvitationResponse, error)
	AcceptCredential(context.Context, *common.AcceptCredentialRequest) (*common.AcceptCredentialResponse, error)
	ListConnections(context.Context, *common.ListConnectionsRequest) (*common.ListConnectionsResponse, error)
	ListCredentials(context.Context, *common.ListCredentialsRequest) (*common.ListCredentialsResponse, error)
}

// UnimplementedCloudAgentServer can be embedded to have forward compatible implementations.
type UnimplementedCloudAgentServer struct {
}

func (*UnimplementedCloudAgentServer) RegisterCloudAgent(context.Context, *common.RegisterCloudAgentRequest) (*common.RegisterCloudAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCloudAgent not implemented")
}
func (*UnimplementedCloudAgentServer) GetEndpoint(context.Context, *common.EndpointRequest) (*common.EndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEndpoint not implemented")
}
func (*UnimplementedCloudAgentServer) AcceptInvitation(context.Context, *common.HandleInvitationRequest) (*common.HandleInvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptInvitation not implemented")
}
func (*UnimplementedCloudAgentServer) AcceptCredential(context.Context, *common.AcceptCredentialRequest) (*common.AcceptCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptCredential not implemented")
}
func (*UnimplementedCloudAgentServer) ListConnections(context.Context, *common.ListConnectionsRequest) (*common.ListConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (*UnimplementedCloudAgentServer) ListCredentials(context.Context, *common.ListCredentialsRequest) (*common.ListCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCredentials not implemented")
}

func RegisterCloudAgentServer(s *grpc.Server, srv CloudAgentServer) {
	s.RegisterService(&_CloudAgent_serviceDesc, srv)
}

func _CloudAgent_RegisterCloudAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.RegisterCloudAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).RegisterCloudAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/RegisterCloudAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).RegisterCloudAgent(ctx, req.(*common.RegisterCloudAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_GetEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).GetEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/GetEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).GetEndpoint(ctx, req.(*common.EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_AcceptInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.HandleInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).AcceptInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/AcceptInvitation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).AcceptInvitation(ctx, req.(*common.HandleInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_AcceptCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.AcceptCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).AcceptCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/AcceptCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).AcceptCredential(ctx, req.(*common.AcceptCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/ListConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).ListConnections(ctx, req.(*common.ListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAgent_ListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAgentServer).ListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didcomm.CloudAgent/ListCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAgentServer).ListCredentials(ctx, req.(*common.ListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didcomm.CloudAgent",
	HandlerType: (*CloudAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCloudAgent",
			Handler:    _CloudAgent_RegisterCloudAgent_Handler,
		},
		{
			MethodName: "GetEndpoint",
			Handler:    _CloudAgent_GetEndpoint_Handler,
		},
		{
			MethodName: "AcceptInvitation",
			Handler:    _CloudAgent_AcceptInvitation_Handler,
		},
		{
			MethodName: "AcceptCredential",
			Handler:    _CloudAgent_AcceptCredential_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _CloudAgent_ListConnections_Handler,
		},
		{
			MethodName: "ListCredentials",
			Handler:    _CloudAgent_ListCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "canis-didcomm-cloudagent.proto",
}
