// Code generated by mockery v1.0.0. DO NOT EDIT.

package indy

import mock "github.com/stretchr/testify/mock"

// MockStorageProvider is an autogenerated mock type for the StorageProvider type
type MockStorageProvider struct {
	mock.Mock
}

// OpenStore provides a mock function with given fields: _a0
func (_m *MockStorageProvider) OpenStore(_a0 string) (Store, error) {
	ret := _m.Called(_a0)

	var r0 Store
	if rf, ok := ret.Get(0).(func(string) Store); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
